import React, { Component } from 'react';
import renderer from 'react-test-renderer';
import { shallow, configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import ErrorBoundary from '.';

configure({ adapter: new Adapter() });
class ComponentWithError extends Component {
  render() {
    return (
      <div>
        <input type="text" value={null} />
      </div>
    );
  }
}
describe('ErrorBoundary', () => {
  it('renders correctly', () => {
    const tree = renderer
      .create(<ErrorBoundary> Test </ErrorBoundary>)
      .toJSON();

    expect(tree).toMatchSnapshot();
  });

  it('displays error message on error generated by child', () => {
    const wrapper = shallow(
      <ErrorBoundary>
        <ComponentWithError />
      </ErrorBoundary>,
    );
    wrapper.setState({ hasError: true });
    console.log(wrapper.debug());
  });
});
